name: Update Activity Log

on:
  push:
    branches: [main]
  pull_request:
    types: [closed]

jobs:
  update-activity-log:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Get commit info
        id: commit
        run: |
          echo "author=$(git log -1 --pretty=format:'%an')" >> $GITHUB_OUTPUT
          echo "message=$(git log -1 --pretty=format:'%s')" >> $GITHUB_OUTPUT
          echo "timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> $GITHUB_OUTPUT
          echo "files=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | jq -R -s -c 'split(\"\n\")[:-1]')" >> $GITHUB_OUTPUT

      - name: Read existing activity log
        id: readlog
        run: |
          if [ -f public/activity-log.json ]; then
            cat public/activity-log.json
          else
            echo "[]"
          fi > activity-log.json

      - name: Append new activity
        id: updatelog
        run: |
          jq --arg author "${{ steps.commit.outputs.author }}" \
             --arg message "${{ steps.commit.outputs.message }}" \
             --arg timestamp "${{ steps.commit.outputs.timestamp }}" \
             --argjson files "${{ steps.commit.outputs.files }}" \
             '. += [{"timestamp": $timestamp, "author": $author, "message": $message, "files": $files}]' \
             activity-log.json > activity-log-updated.json
          mv activity-log-updated.json public/activity-log.json

      - name: Commit and push activity log
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add public/activity-log.json
          git commit -m "chore: update activity log [skip ci]" || echo "No changes to commit"
          git push